import Head from "next/head";
import About from "../components/About";
import FishingBoats from "../components/FishingBoats";
import Hero from "../components/Hero";
import Layout from "../components/Layout";
import Reviews from "../components/Reviews";

export default function Home() {
  return (
    <Layout>
      {/* Metadata */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Content */}
      <Hero />
      <FishingBoats />
      <About />
      <Reviews />
    </Layout>
  );
}
