import Head from "next/head";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <Layout>
      {/* Metadata */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Content */}
      <h1>Hello World!</h1>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam magni
        quidem dignissimos fugiat? Modi neque labore non qui. Necessitatibus,
        pariatur.
      </p>
    </Layout>
  );
}
